### ISSUE TITLE
¿How to install?

### ISSUE THREAD

**Issue by Milen4o** [taobataoma/meanTorrent#100]
Can you explane enyone how to install that from the begining with the istalation of the localhost y the database. I install lamp but this is not working. Thanks

**Comment by Wralui** [comment]
Everything is explained, you just need to follow the instructions, but just an advice, don't run a Tracker if you can't understand basics.

**Comment by Milen4o** [comment]
I will not run tracker. Just instal for test user. I have nginx server and mongodb. I follow the seps but it's not working. npm star trigger error missing script start. node js version is not suported too. 
npm run start:prod trigger errors too and etc.

**Comment by Milen4o** [comment]
I found the solution. Just downgrade the ubuntu 18 and you are good to go.
