### ISSUE TITLE
install

### ISSUE THREAD

**Issue by ghost** [taobataoma/meanTorrent#110]
hello i have PM' you on your skype <:)

**Comment by ghost** [comment]
can someone help me install it ? i will pay for it

**Comment by RoyRiv3r** [comment]
I think this project is dead, it's been long time since i didn't see taobataoma, also i remember that he didn't finish it completely, there are a lot of things missing and unsecure ...

**Comment by ghost** [comment]
> I think this project is dead, it's been long time since i didn't see taobataoma, also i remember that he didn't finish it completely, there are a lot of things missing and unsecure ...

bloody fucking hell ! nothing seems so good as this ! :( thats just sad!

**Comment by RoyRiv3r** [comment]
Yeah I was the one who asked him to put stuff on his tracker, https://github.com/taobataoma/meanTorrent/issues/20
I suggest many things but unfortunately he didn't finish it, well if someone else can fork and maybe continue in the future, lets hope...

**Comment by ghost** [comment]
> Yeah I was the one who asked him to put stuff on his tracker, #20
> I suggest many things but unfortunately he didn't finish it, well if someone else can fork and maybe continue in the future, lets hope...

I really hope because there is not a projekt like this on github and that have so many features !

**Comment by ghost** [comment]
> Yeah I was the one who asked him to put stuff on his tracker, #20
> I suggest many things but unfortunately he didn't finish it, well if someone else can fork and maybe continue in the future, lets hope...

and  you cannot install it ?  :(

**Comment by RoyRiv3r** [comment]
I don't know i didnt try since then.  
But I think you still can, but there are a lot of changes and update from prerequisites and stuff, if you have errors it's normal this project didn't get any update and if you don't know anything about MEAN, you are kinda screwed ...

**Comment by ghost** [comment]
> I don't know i didnt try since then.
> But I think you still can, but there are a lot of changes and update from prerequisites and stuff, if you have errors it's normal this project didn't get any update and if you don't know anything about MEAN, you are kinda screwed ...

well okay the only error i have now is that the Bower will not install :S do you have a solution for that ?

**Comment by ghost** [comment]
> I don't know i didnt try since then.
> But I think you still can, but there are a lot of changes and update from prerequisites and stuff, if you have errors it's normal this project didn't get any update and if you don't know anything about MEAN, you are kinda screwed ...

can you add me on discord ? henrik#9081 :) thats a bit easyer

**Comment by RoyRiv3r** [comment]
No sorry i don't know, and if you have to fix a dead project it's gonna take so much time than going on new & updated like this one https://github.com/HDInnovations/UNIT3D-Community-Edition and you can have support

**Comment by ghost** [comment]
> No sorry i don't know, and if you have to fix a dead project it's gonna take so much time than going on new & updated like this one https://github.com/HDInnovations/UNIT3D-Community-Edition and you can have support

okay that one sucks i have tryed it :) but thanks :)
