### ISSUE TITLE
Multiple .srt files

### ISSUE THREAD

**Issue by icecore2** [taobataoma/meanTorrent#13]
it's a "must" for packages when uploaded

**Comment by taobataoma** [comment]
@icecore2 what did you means? the subtitle files can be a .rar or .zip or .7z package and single file with .srt or .ass.

**Comment by icecore2** [comment]
@taobataoma it would be more secured for users to see actual .srt  file and prevent from locking for compressed files would be good :)

**Comment by taobataoma** [comment]
@icecore2   all of the subtitle files is would be compressed (rar & zip & ...)?

**Comment by icecore2** [comment]
@taobataoma if selection will be multiple srt files, would be nice to be compressed.(zip, rar...)

**Comment by taobataoma** [comment]
@icecore2 Maybe users just need one of those files

**Comment by icecore2** [comment]
The idea is: 
Make it as a list if more than 1 .srt files uploaded.
The list can be selected with checkboxes, 
- File names appeard as links(if pressed on name it download a specific)
- If selected more than 1, it creates a compressed file with selected.

All this is an idea i suggestinng for better .srt files downloading :)

**Comment by taobataoma** [comment]
@icecore2 thanks, But most of the time, each user might just have to download one of his favorite files
