### ISSUE TITLE
 npm run problem 

### ISSUE THREAD

**Issue by polashraj** [taobataoma/meanTorrent#14]
hi i am trying to run your meanTorrent and get this error .

[22:40:43] Starting 'less'...
Potentially unhandled rejection [2] '../../../../public/lib/bootstrap/less/mixins/vendor-prefixes.less' wasn't found. Tried - /home/talmuri/meanTorrent/public/lib/bootstrap/less/mixins/vendor-prefixes.less,../../../../public/lib/bootstrap/less/mixins/vendor-prefixes.less in file /home/talmuri/meanTorrent/modules/core/client/less/mt-var.less line no. 3

**Comment by taobataoma** [comment]
@polashraj hi, are you already run npm install command? it will auto run bower install to install bootstrap css lib, if bootstrap is installed correct, the file vendor-prefixes.less will existed in .../meanTorrent/public/lib/bootstrap/less/mixins/vendor-prefixes.less, if the file is not existed, please run bower install to install bootstrap manual.

same question here #4

**Comment by polashraj** [comment]
yes , i get this when i try to run "npm start" command

**Comment by polashraj** [comment]
i run it , thank you for your support

**Comment by taobataoma** [comment]
@polashraj  That`s very good!
