### ISSUE TITLE
Smtp configuration

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#18]
How to set up smtp mail?
Port, authentication, password, stmp.domain.com?

**Comment by taobataoma** [comment]
the smtp settings guide is in project readme.md at github.ocm

**Comment by Nemcio** [comment]
I do not know where to look and how to set up smtp. Can you write how to do?

**Comment by taobataoma** [comment]
@Nemcio in config/env/development.js and production.js
```javascript
  mailer: {
    from: process.env.MAILER_FROM || 'admin@chd.im',
    options: {
      service: process.env.MAILER_SERVICE_PROVIDER || 'Gmail',
      auth: {
        user: process.env.MAILER_EMAIL_ID || 'taobataoma@gmail.com',
        pass: process.env.MAILER_PASSWORD || 'ykyghbmpjfdliyph'
      }
    }
  },
```

**Comment by Nemcio** [comment]
I have entered my gmail account data and it does not work for password recovery or invitations.
Can I use my domain name mails? Where to enter port (25)?

**Comment by taobataoma** [comment]
@Nemcio maybe you can do some custom setting, meanTorrent origin from MEAN, and MEAN used [nodemailer](https://nodemailer.com/about/), you can seed how to custom it and modify the config options. you need to study and do it yourself

**Comment by Nemcio** [comment]
There is something wrong because gmail does not work too.
  mailer: {
    from: process.env.MAILER_FROM || 'admin@mydomain.ltd',
    options: {
      service: process.env.MAILER_SERVICE_PROVIDER || 'Gmail',
      auth: {
        user: process.env.MAILER_EMAIL_ID || 'my login@gmail.com',
        pass: process.env.MAILER_PASSWORD || 'my password'
      }
    }
  },
Did not work. That's why I'm reporting.
nodemailer I read I tested. did not work.

**Comment by taobataoma** [comment]
@Nemcio but gmail is work fine on localhost and demo site. your gmail need twice verify password?
maybe you need check your gmail login settings.

**Comment by Nemcio** [comment]
@taobataoma does not need. I tested on 8 gmail emails. Does not work on any.

**Comment by taobataoma** [comment]
@Nemcio  do you need vpn to connect to gmail and send mail?

**Comment by Nemcio** [comment]
No

**Comment by Nemcio** [comment]
Which TCP/UDP ports are used to send mail?

**Comment by Nemcio** [comment]
OK works.
You need to open the gmail ports on the proffessional server in the firewall (port in OUT).
This is a bad idea on dedicated vps production servers.
Google has a limit of 500 emails per hour.
Blocks and bans IP server.
It is better to use local srwser mails using smtp (port 25,465,587) and sendmail.
If you want people not to complain then think about it.

**Comment by taobataoma** [comment]
@Nemcio fine, your mail system is worked. the mail option will be keep all. thanks.
