### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#22]
@taobataoma often do updates. You can write how to update on the server so that each time you do not install again?

**Comment by taobataoma** [comment]
@Nemcio meanTorrent is work in progress now, and has not published, so you can not see tags like v0.0.1 etc. all the functions is my plan is first event now. after published, i should think about server update and install automate by a admin menu command.

**Comment by Nemcio** [comment]
@taobataoma how are you updating now? Are you installing every time?

**Comment by taobataoma** [comment]
@Nemcio , no , not reinstall every time, i create a folder and git clone meanTorrent first,  and install,
when i update(push) any code , i run 'git pull' in meanTorrent folder, it will update all new change from github repo, then start it.

**Comment by Nemcio** [comment]
@taobataoma and that's enough because I already installed 40 times because I did not know how to update it.
PS
I started to do the translation. Are you interested?

**Comment by taobataoma** [comment]
@Nemcio Of course, when release it, i can add a new translate configure item into config.js and a new choice option for user.

**Comment by Nemcio** [comment]
@taobataoma I add an option for each installation. About 300 lines have already been translated.

**Comment by taobataoma** [comment]
@Nemcio After the release, you can give me a complete translation file.

**Comment by nearsou** [comment]
@Nemcio What language do you translate ?
@taobataoma Im about to translate in my native language which is French, I'll give it to you when I finish 💯

**Comment by Nemcio** [comment]
@nearsou I'm from Poland so I'm translating to Polish.
