### ISSUE TITLE
Opening in a new tab

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#23]
Is it possible to change this to open in the same window?

**Comment by taobataoma** [comment]
@Nemcio what do you means?

**Comment by Nemcio** [comment]
As you enter the torrent description page, it opens in a new tab of firefox. They can open in the same firefox tab.

**Comment by taobataoma** [comment]
@Nemcio your means torrent detail page is open in new tab now, and want to open it in the same tab like other links?

**Comment by nearsou** [comment]
Agreed, letting users open a new tab (not obligatory) by themself would be great 👍

**Comment by Nemcio** [comment]
Thanks.
They already open in the same window.

**Comment by nearsou** [comment]
Can you please close thread when problem is solved, thx :)
