### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#25]
Can you add after adding pictures from your computer:
![screenshot_20171108_150140](https://user-images.githubusercontent.com/2566039/32553191-718149b6-c496-11e7-9ad6-c90f5a0c0cf3.png)
Add an option with url:
![screenshot_20171108_150538](https://user-images.githubusercontent.com/2566039/32553213-80789988-c496-11e7-9d88-d3e652a1458a.png)

**Comment by taobataoma** [comment]
@Nemcio In order to reduce link errors, I think pictures should be uploaded locally, and it doesn't add too much tedious work

**Comment by Nemcio** [comment]
@taobataoma It's about uploading by url. How to maz on the computer 200-500 files in the directory it is doing the cumbersome.
