### ISSUE TITLE
Adding your own pages

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#26]
How can you describe the movies, games, etc., add other pages?
![screenshot_20171108_150957](https://user-images.githubusercontent.com/2566039/32553440-3ec6e534-c497-11e7-8494-a019783ffb7e.png)
IMDB Link：http://www.imdb.com/title/
TMDB Link：https://www.themoviedb.org/movie/
Other page 1: http://.......
Other page 2: http:/........
If it is possible?

**Comment by nearsou** [comment]
Do you mean modify torrent information ? I wonder if you can let user the choice to modify the whole page.

**Comment by Nemcio** [comment]
No. I want to be able to add links with descriptions from other portals. Not only with IMDB and TMDB.

**Comment by nearsou** [comment]
Oh i see what you mean, but isnt more interesting if you can edit the whole page instead and not just only add page 👍

**Comment by taobataoma** [comment]
@Nemcio I need further consideration for this, I think it doesn't make much sense

**Comment by nearsou** [comment]
Yes this is what I was thinking this is more complicate, what do you think if we can edit this ? 
![0ffcdbe98a](https://user-images.githubusercontent.com/20752723/32604011-329a01e6-c54c-11e7-878b-189ba73d0ef8.png)
And I have a question, did this informations stored somewhere in the cms or just taken from api

**Comment by Nemcio** [comment]
@taobataoma Each country has its own portals with reviews of films and games.
In my country there is a very large portal with reviews of films and games that use 80%.
With TMDB and IMDB I did not use it because it is on these national portals is everything.
The film even has the Maven API.
