### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#27]
You can add to README.md:
By adding a language:
Add to `/config/assets/default.js`:
`'public/lib/bootstrap-markdown/locale/bootstrap-markdown.zh.js'`
`'public/lib/bootstrap-markdown/locale/bootstrap-markdown.new.js'`
and
`'modules/core/client/app/trans-string-en.js',`
`'modules/core/client/app/trans-string-new.js',`
To `/config/assets/production.js`
`'public/lib/bootstrap-markdown/locale/bootstrap-markdown.zh.js',`
`'public/lib/bootstrap-markdown/locale/bootstrap-markdown.new.js',`

**Comment by taobataoma** [comment]
@Nemcio thanks, already add it.
