### ISSUE TITLE
Collections tab

### ISSUE THREAD

**Issue by nearsou** [taobataoma/meanTorrent#28]
> - 31.Complete movie collections support, Admin can create a collection and insert any movie into it, user can view collection and download all torrents of the collection.

I didn't find options where can 'admin' or 'oper' put torrent to collection like this http://chd.im:3000/collections

**Comment by taobataoma** [comment]
@nearsou menu item collections only show/list the collection for normal users. if you want create a collection from a torrent, you need open the torrent detail page and you can find the operation button in admin tab. if the movie not belong to any collection, the operation button will be hidden.

**Comment by taobataoma** [comment]
@nearsou if the movie has not belong to any collection(data from tmdb), the operation button will be hidden.

**Comment by nearsou** [comment]
Oh! I see now, its from TMDB Collection not from the site himself, well thanks for the answer 👍
