### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#29]
I showed my work to a few friends. They like it very much. They said that if there was an admin panel in which you could set all the options that need to be changed in the configuration files then this would be the best tracker they have seen.
But everyone said that he did not want to register his name and name with just a nick.
Is there a possibility of such a modification?
![screenshot_xxx1](https://user-images.githubusercontent.com/2566039/32585937-2ccfd9f8-c500-11e7-8abe-d34ab7fe1bd4.png)

**Comment by nearsou** [comment]
Yes this is because the cms is also compatible with social network :)
I dont know how is structured but if its not hard for @taobataoma an alternative would be nice 👍

**Comment by taobataoma** [comment]
@Nemcio @nearsou yes, I already do this, and can compatible with social network.
