### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by HDVinnie** [taobataoma/meanTorrent#3]
Can you please bring the demo site up?

**Comment by taobataoma** [comment]
oh, yes, I am deploying demo site now, it will be opened at [http://chd.im:3000](http://chd.im:3000), please retry it later.

**Comment by HDVinnie** [comment]
Nice thank you! Project looks good so far. Are you familiar with laravel?

**Comment by taobataoma** [comment]
No, i didn`t familiar laravel, what about it?
