### ISSUE TITLE
Edition

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#30]
How can you edit a torrent theme to change a movie description or add a new torrent after reset passkey?

**Comment by taobataoma** [comment]
@Nemcio for movie and tvserial, uploader can not modify the description, but admin can update whole info from TMDB by current language setting from torrent detail page admin panel, for other type torrent, admin and uploader can edit description on torrent detail page, you can see a link below torrent overview.

do you have any error when you upload new torrent after reset passkey?

**Comment by Nemcio** [comment]
Does the passkey automatically update all inserted torrents or do you need to rewrite the topic?

**Comment by taobataoma** [comment]
@Nemcio  Sorry, How to write to passkey is not something you need to consider. If you have a problem after reset passkey, you can ask it here. If you haven't done the test yourself, please test it first then post a new topic at here if you get any problem, thanks.

**Comment by Nemcio** [comment]
At least you can do editing Video NFO?

**Comment by taobataoma** [comment]
@Nemcio sorry, NFO can not be modify
