### ISSUE TITLE
Not in TMDB

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#32]
How to add a video that is not in TMDB?

**Comment by nearsou** [comment]
You know that you can create and add your own serial/movie from TMDB right ?

**Comment by taobataoma** [comment]
@Nemcio I already think about this issues, TMDB is a open and great video info site and provider free API, i agree @nearsou `s idea, you can create a new item into TMDB, we used data of TMDB, so we need contribution to TMDB.

**Comment by Nemcio** [comment]
@taobataoma Not everyone wants to make private videos, such as local sports events or events. So how to add?

**Comment by taobataoma** [comment]
@nearsou Obviously, you don't have to watch the demo.site carefully, there are many types of torrents in the menu, the sports video you want to say should have their own categories, not in the movie category, if no suitable category should be into other categories.

**meanTorrent has more function, please check it carefully.**
