### ISSUE TITLE
All torrent on simple clic on torrent in menu user or subcat

### ISSUE THREAD

**Issue by Jul13n** [taobataoma/meanTorrent#34]
first of all, I would like to congratulate you on your work.
It's been 10 days since I installed your code, explored and put in real situation.
the script is clean, fast, and low resource utilization.

However, I have a question:
1 / How to display all torrent in torrents/movie (is a example) without the need to select a tag.
2 / How to create a link to domain.tld/torrents to display all torrents of all categories.

I hope you'll be able to clear me up.

best regard

Jul13n

**Comment by nearsou** [comment]
Hello there, this feature is not available yet, maybe in the futur if @taobataoma wants to :)

**Comment by taobataoma** [comment]
@Jul13n what do you means? you want a menu item link to list all torrents of all categories? in meanTorrent, if you click a menu item(like torrents/movie), system will list all movie torrents and without tag filter, when you select some tag then  filter movie to show.

if you showed all torrents of all categories, it`s to more and mixed together, why you need this feature? i think the normal user to download some torrents, should select a category and select some torrent to download.

**Comment by Jul13n** [comment]
hello @nearsou  @taobataoma  , thanks for your reply.

On your demo site, if I click on torrent / movie for example, I have a list that appears.
But on mine, if I click on torrent / movie, I do not have a list that is displayed except if I choose a tag.

I put a video to show you : https://hostr.co/ouBkoF87sKXp

best regard,

Jul13n

**Comment by taobataoma** [comment]
@Jul13n haha, give me a video is a good way.
on demo show a list but not a your site, because your count movies is not more than six, the logic of meanTorrent, if you do not select any tags, it will show all torrents, but first six is showed on top, and other showed in list, if you select any tags, it will show all result by filter in list, because the top six has not any more info can read, only a big picture for nice looking.
hope this help you.

**Comment by Jul13n** [comment]
Hello @taobataoma  how are you ?
you're right, after adding the torrent, the list appears well.
Thank you for your support,
I think to come back for advice in a short time.
I take this opportunity to send you the translation in French that I'm almost done

Best regard

Jul13n

**Comment by taobataoma** [comment]
@Jul13n thanks, here is a brother @nearsou is from France too, him is translate it also.
meanTorrent need more guy from other country to translate, but maybe i need to rearrange all the strings, make it more clean, it won`t be long.

**Comment by nearsou** [comment]
@Jul13n oh well you are from France too ^^ how much did you already finish, i'm in middle of translation so if you are almost finished just give it to him 👍

**Comment by Jul13n** [comment]
hello @nearsou 
I think I have finished for the weekend. on the other hand the translation and with additions that must be deleted because I made according to our needs. 
(example: translation of my category, additional tags etc ...)
