### ISSUE TITLE
Announce URL with passkey

### ISSUE THREAD

**Issue by tojoaijo** [taobataoma/meanTorrent#35]
Hello,
Firstly, thank you for your great work, it's working fine :)

I have a suggestion about the announce URL, how if we put directly the passkey on the announce URL on the upload page? So the user don't need to redownload the file after upload it to begin the seed?

And, have you a forum about request or issue?

Thank you and the best of wishes for the future ;)

**Comment by nearsou** [comment]
Hi @tojoaijo, do you mean when you create torrent with bittorent for example, you put the entire announce url + passkey directly ? I think this is a good idea, but I still wonder why @taobataoma make it this way, maybe for some reason.

**Comment by taobataoma** [comment]
@tojoaijo @nearsou I think this is can be accepted, you can put any announce url + any passkey directly if you want, and server will change it to the setting announce base url(such as: http://chd.im/announce) when you upload and rewrite passkey into announce url(such as: http://chd.im/announce/somePasskey) when you download a torrent file. so, you will not redownload the torrent file after upload and can begin the seed by the torrent file.

this is only a idea now, if it`s ok, let me do it later.

**Comment by tojoaijo** [comment]
Hi @taobataoma @nearsou 
Thank you guys :)
I'm new at nodejs but I have a team here who want that concept working, we will tell you if we will find a solution
PS: yes, we want to use it with PRIVATE TRACKER

**Comment by tojoaijo** [comment]
@taobataoma I have sending a request on your skype but for the QQ, I don't know how to search the group you tell on the REAME

**Comment by taobataoma** [comment]
@tojoaijo you can add me by skype: taobataoma

**Comment by tojoaijo** [comment]
request sent :)

**Comment by taobataoma** [comment]
@tojoaijo @nearsou auto change announce url to setting value when upload on PRIVATE  TRACKER MODE now, so you can  put in any announce url when you create a torrent file, and will not redownload the torrent file after upload.

but you can not announce any data to tracker when the torrent is not reviewed by administrator.

**Comment by taobataoma** [comment]
@tojoaijo sorry, I don't understand your question. the announce url configure item in file 'config/env/torrents.js' -> 'announce' section.

**Comment by tojoaijo** [comment]
sorry but I don't understand what to do :)
can you make an example, please?

**Comment by taobataoma** [comment]
> I have a suggestion about the announce URL, how if we put directly the passkey on the announce URL on the upload page? So the user don't need to redownload the file after upload it to begin the seed?

now, like you said, you can put directly the passkey on the announce URL when you create the new torrent file by any create tools, so you do not need to redownload the file after upload.

but you know, you passkey save in torrent file (announce url) on server is not safety, so server will auto change the torrent announce url to the configure setting value, the config item is in file 'config/env/torrents.js', such as:

```javascript
    announce: {
      url: 'http://chd.im:3000/announce',
      ......
    },
```

when user to download this torrent file, system will auto append his passkey after the announce url, such as: `http://chd.im:3000/announce/passkey-value-of-user`.

before you start meanTorrent server, you should first view the config file and check every configure item and change to you wanted value, thanks.

**Comment by tojoaijo** [comment]
Ok, I understand it now and it's working fine :)
Many thanks to your good work
Now, I will put a message to show the uploader what's the url announce with his passkey to use when he create the torrent, because not all clients know what his passkey

**Comment by tojoaijo** [comment]
Hello @taobataoma , how are you?
Sorry for disturbing you but can you help me how to show this announce URL with passkey on the upload page? I tried several things but that's not working

**Comment by tojoaijo** [comment]
Great job @taobataoma , many thanks :)
If I have another suggestion or improvement, I will report to you
