### ISSUE TITLE
Suggestion: Is it possible to hide menu for non logged in

### ISSUE THREAD

**Issue by Phogo** [taobataoma/meanTorrent#39]
Hi,

Would it be possible to hide all information (menu, torrents etc) unless the user is logged in?

Would make it more private.

Thank you.

**Comment by taobataoma** [comment]
@Phogo In project readme new feature No. 40
>Admin can configure to hide all menu header for guest users, usefully for private tracker mode

The configure setting is in file config/env/torrent.js

```javascript
sign: {
      openSignup: true,
      signUpActiveTokenExpires: 60 * 60 * 1000 * 24,
      allowSocialSignin: false,
      showMenuHeaderForGuest: true,  //change this to false to hide menu header
      showDemoSignMessage: true
    }
```

**Comment by Phogo** [comment]
Fantastic. I should maybe I should read more closely. Thank you very much!
