### ISSUE TITLE
Port setting

### ISSUE THREAD

**Issue by tojoaijo** [taobataoma/meanTorrent#41]
Hello @taobataoma ,
Just a question: can we use the domain of the site on port 80 and the announce tracker on other port like 3000?
e.g: site address: http://ch.com
Announce url: http://ch.com:3000/

**Comment by taobataoma** [comment]
@tojoaijo the web and tracker must used same port now.

**Comment by tojoaijo** [comment]
OK, and thank your for that precision :)
