### ISSUE TITLE
Hiding meanTorrentConfig from source code

### ISSUE THREAD

**Issue by Phogo** [taobataoma/meanTorrent#43]
Hi,

Please excuse my ignorance, but is there any way to hide the config from the source code? If you view the source you can see the full torrents.js config. This exposes alot of information, some being sensitive. Thanks. 

EG.

`<script type="text/javascript">
    var user = null;
    var env = "production";
    var meanTorrentConfig =`

**Comment by Answer-Man** [comment]
This should have been fixed in this commit https://github.com/taobataoma/meanTorrent/commit/2caa625f0ed05a8451a8cef48fb74a5c441a320e.

**Comment by Phogo** [comment]
Thank you. Yes, this has now hidden the tmdb key, is it possible to hide all that config?

**Comment by taobataoma** [comment]
@Phogo some configure item settings used on browser to do pre check, so some settings must include source code, but the important items is not include if do not used on browser.

**Comment by Phogo** [comment]
@taobataoma - Ok no problem. Thanks for the explanation
