### ISSUE TITLE
Problem with maker group

### ISSUE THREAD

**Issue by tojoaijo** [taobataoma/meanTorrent#44]
Hello,
I want to create a maker and I have an error
![create_maker_group](https://user-images.githubusercontent.com/5299914/33832025-68384242-de8b-11e7-9375-38f28428b238.PNG)

But when I checked on "Managed Uploader", I can see the maker group, but I can't add member to this group
![uploader_maker_group](https://user-images.githubusercontent.com/5299914/33832066-955ad384-de8b-11e7-9e93-8eb3f2fe52c0.PNG)

**Comment by nearsou** [comment]
@tojoaijo I don't have this bug, did you update your repertory properly ? Even in http://chd.im:3000 it works fine.

**Comment by taobataoma** [comment]
@tojoaijo add group member is not admin`s work, only for group founder, you can find the operation button for 'add member' in maker group detail page.

**Comment by tojoaijo** [comment]
thank you guys, I will rebuild my system now and I retry the installation
Perhaps, I have made something wrong on the settings on torrent.js

**Comment by tojoaijo** [comment]
I have trying to reinstall the app and I have these error when launching "npm install":
![install_error_1](https://user-images.githubusercontent.com/5299914/33871677-86dbfcfe-df24-11e7-93c5-fa0541f2022d.PNG)
![install_error_2](https://user-images.githubusercontent.com/5299914/33871683-8d219d30-df24-11e7-834d-4ed10ad8c8cb.PNG)

**Comment by tojoaijo** [comment]
and the creation of maker group doesn't work now for my system
I have make a fresh installation

**Comment by tojoaijo** [comment]
@nearsou can you try to make a fresh installation and make a test to create a maker group, please?
I want to know if that OS who causes this issues

**Comment by taobataoma** [comment]
@tojoaijo hi, if you still has this error, please copy all error message on console screen to me, thanks.

**Comment by tojoaijo** [comment]
Hi @taobataoma ,
Thank you for your help.
All error I have is there on these screenshot.
On my previous systeme that i build, I can create maker group successfully and I can add member at (I have build that system on November). I have updated as it have a new commit on github.
And now, I have a new server, and I have installed the meanTorrent app after git cloned the repository on github. I can installing it but just I have these WARNING on these screenshot and I can't create a maker group.
After creating the maker group, I can see this on the console
![groupe_maker_console](https://user-images.githubusercontent.com/5299914/33929213-b4466f82-dff9-11e7-8f43-ba4a31d5b442.PNG)
And I have this error when creating the group
![create_maker_group](https://user-images.githubusercontent.com/5299914/33929232-c872c3c0-dff9-11e7-971b-a3cb29f7ef25.PNG)
But when I go to "Torrent Maker Group", I can see the group that I created but I can't add member to it, I have an error like on the previous screenshot

Is there a log file where can I see the error?

**Comment by nearsou** [comment]
@tojoaijo I tried to install it same OS as yours, and it works fine but however there is some tricky thing to do
- First do you have full permission of your repertories (must be root)
- Did you know when you make a fresh installation you need to delete the data base mongodb before install new meantorrent  `/data/db/` it causes conflict
- Which version of mongo you have `mongo --version` it must be 3.6 not bellow
- For this problem  ![il](https://user-images.githubusercontent.com/5299914/33871683-8d219d30-df24-11e7-834d-4ed10ad8c8cb.PNG)  ![ilm](https://user-images.githubusercontent.com/5299914/33871677-86dbfcfe-df24-11e7-93c5-fa0541f2022d.PNG) try after finished installation to rebuild it `npm rebuild --unsafe-perm=true --allow-root` with permissions
Hope this help you

**Comment by tojoaijo** [comment]
Thank you for you help @nearsou 
> First do you have full permission of your repertories (must be root)
Yes, I have full permission because it's a new server that I created

> Did you know when you make a fresh installation you need to delete the data base mongodb before install new meantorrent /data/db/ it causes conflict
I am on a new server, and I just installed the mongodb server.
My version of mongo is 3.6.0
![mongo_version](https://user-images.githubusercontent.com/5299914/33938203-9e42f0f2-e017-11e7-8eed-aa585b5b06ef.PNG)

I have rebuild all the system now (reinstalled OS, reinstalled all Prerequisites, reinstalled meanTorrent), and stil have the same issue that I have the error when creating a maker group

This is the specificity of my server:

- OS: Debian 8

- Node: v8.9.3

- Mongodb: 3.6.0

- Bower: 1.8.2

- NPM: 5.6.0

**Comment by nearsou** [comment]
@tojoaijo Oh I see now your issue, I got the same bugs, maker is created but with error "something went wrong", you can see them from /about/maker but it doesnt appear in upload page ![https://puu.sh/yFzxl/0ca384b1e0.png](https://puu.sh/yFzxl/0ca384b1e0.png)
also another bug appear: ![https://puu.sh/yFyaL/3ec425ddd0.png](https://puu.sh/yFyaL/3ec425ddd0.png) the slidebar attribut video is on top from torrent page shows up directly and can't quit it, I think it comes from compatibility issue with linux system maybe ? 
In windows server installation, it create the maker without error but not appear when you upload.  @taobataoma

**Comment by taobataoma** [comment]
@tojoaijo @nearsou This issue looks like write in maker db successfully, but save group into user db failed, I can't figure out why, maybe you need more tips. Do you create a group and got a 'something went wrong' every time?

@nearsou 
>also another bug appear: https://puu.sh/yFyaL/3ec425ddd0.png the slidebar attribut video is on top from torrent page shows up directly and can't quit it,

this is because I modify the control 'angular-side-overlay', and finished yesterday, so it showing on top and can`t cancel it at The day before yesterday, but I think this do not involve of this maker create issue.

**Comment by tojoaijo** [comment]
> Do you create a group and got a 'something went wrong' every time?

Yes, I always have this error when creating a group`(everytime)

**Comment by tojoaijo** [comment]
@nearsou what OS do you use on linux to build the app?

**Comment by tojoaijo** [comment]
@taobataoma what is the OS you use for the demo site?

**Comment by taobataoma** [comment]
@tojoaijo I used centOS 7

**Comment by tojoaijo** [comment]
thanks, I'm not used with centOS but I will to built with it now

**Comment by taobataoma** [comment]
@tojoaijo can I remote ssh to your server and debug this issue?

**Comment by tojoaijo** [comment]
@taobataoma just few minutes, I will create you an access

**Comment by tojoaijo** [comment]
@taobataoma I will send you the access by mail or on your skype

**Comment by tojoaijo** [comment]
@nearsou : our hero @taobataoma have seen that the mongodb was the source of the issue, I use the latest version of mongodb server which is 3.6
He has seen that version 3.5 and 3.6 of mongodb is not already stable, the version stable is 3.4
So I have downgrade my mongodb server to 3.4.10 and it's working fine now for the creation of group

@taobataoma like @nearsou said above, when I use admin user: I can't see the group on upload page
![maker_group_upload_page](https://user-images.githubusercontent.com/5299914/33984507-e89e9a3c-e0c8-11e7-82a2-6168adfb330e.PNG)
But when I use a simple user, I can see the group (which the user is member) on upload page
![maker_group_upload_page_user](https://user-images.githubusercontent.com/5299914/33984551-11ab1982-e0c9-11e7-8385-90c91d25669b.PNG)
I don't know if it a bug or if that's how the application works

**Comment by taobataoma** [comment]
@tojoaijo  every group has own members, if you in any group, then them will show list in upload page, but, if you not in any group(although you r admin), then now group showed in upload page. 

admin can create group, but can not used group to upload if admin not in the group.

**Comment by tojoaijo** [comment]
sorry @taobataoma , I think it was just a bug because I can see it on upload page now.

Just before closing this issue, does the download doesn't work if the seeder and leecher are in the same IP address?

**Comment by nearsou** [comment]
Ok nice to see this problem fixed 😄 
So now in some Linux distribution you need to downgrade mongodb, I got it thanks !

> Just before closing this issue, does the download doesn't work if the seeder and leecher are in the same IP address?
--




@tojoaijo what do you mean ?

**Comment by tojoaijo** [comment]
> what do you mean ?

For example, I seed an file with utorrent app and my IP address is 192.168.1.10, and after I make a test to download that files with an another user (another user on meanTorrent) with the same computer (IP address always 192.168.1.10) but with another bitorrent app like Vuze
Does the download can be work with that same IP address? because I tested it and doen't work for me but I don't know if the utorrent app is the problem
(@nearsou if I'm not mistaken, do you speak french too?)

**Comment by taobataoma** [comment]
@tojoaijo I test on local macbook pro, admin is seeding and another user to download, it is work fine, so same ip did not affect download. 
![up-down](https://user-images.githubusercontent.com/7778550/34068008-5b1e9e34-e26f-11e7-9ab0-98b16d53fa53.png)

but, I add a new config setting in torrent.js `announce.downloadCheck.canDownloadOwnSeeding`, you can setting whether user can download from him own seeding, this can prevent users from cheating to improve total ratio.

**Comment by tojoaijo** [comment]
Hello guys,
Thanks for all your help.
@taobataoma thank you for your test
Last friday, I have seen some problem when leeching 1 files by 2 users, just one users can leech the file.
But I will redo my test today and I will poste an issue if I see a problem.

So I close this issue. Thank you guys :)
