### ISSUE TITLE
Problem on creating account

### ISSUE THREAD

**Issue by tojoaijo** [taobataoma/meanTorrent#45]
Hello all,

I am encountering a problem when creating a user:

- when I use a mail address with gmail, I don't have any error, I can create the account successfully

- but when I use other mail domain (like ours "@ipedom.com"), I get an error when I active the account with the link I received in the mailbox
![create_account_error](https://user-images.githubusercontent.com/5299914/34095127-4a0c5b36-e3e1-11e7-95d0-986ee9d94d8c.PNG)

- Or when I checked the account status, I can see that the status of the account is "normal"
![create_account_error3](https://user-images.githubusercontent.com/5299914/34095208-94fb2c26-e3e1-11e7-889a-c4f9ee45e1cd.PNG)

- so I have test to log with the account and I have already the error message
![create_account_error2](https://user-images.githubusercontent.com/5299914/34095224-abdc7634-e3e1-11e7-8c91-773991dbec94.PNG)

- but I have tried to refresh the page and now I can viewed the home page successfully

So were is the problem, perhaps I have put wrong thing on my config?

PS: before, I have created 2 user with that domain mail (@ipedom.com) and I haven't error; I encountered this error since Friday.
And I have make a test to create the account with the same name and login name but just with domain mail "gmail",  I haven't seen any error

**Comment by taobataoma** [comment]
@tojoaijo I think your steps is not sequential, please test again and give me the detail steps and screenshot

NOTE: if you login successfully, the page will be back to before login, so if click sign in on step 2, after login will back to this page, maybe is step 4 you said

**Comment by tojoaijo** [comment]
@taobataoma I have rebuild the app now and I have enabled the mongodb debug.
When I create a account with domain mail GMAIL, I have this on the console:
![gmail](https://user-images.githubusercontent.com/5299914/34107011-9a8162bc-e40b-11e7-8d07-42a3adf03a49.PNG)
And the account creation work correctly
But with another domain (our domain @ipedom.com), I have this on console log:
![ipedom](https://user-images.githubusercontent.com/5299914/34107044-be346006-e40b-11e7-811c-133f5a4a56af.PNG)
If you look at it, you can see that is automaticly activate after he send the mail, so I tested to log directly with the new account (without activate it by the url on the mail) and I can logged correctly
I don't know if our domain is the problem, and I don't have another domain mail to make a test

**Comment by taobataoma** [comment]
@tojoaijo Sorry, I was check the problem of announce these days, no time to focus this issue, now i can check this
like the picture above, a request of POST '/api/auth/signup' and GET '/api/auth/active/:token' was received, these request if from user, your pc can auto check mail and send request? It`s very Strange.

**Comment by tojoaijo** [comment]
No, I haven't an auto check mail on my pc.
But now, I have make a test with another domain mail (@gmx.fr) and I don't have any problem.
Perhaps, it's on our domain mail is the problem

**Comment by tojoaijo** [comment]
we can close this issue now, the problem is solved after some update you have done.
Thanks @taobataoma :)
