### ISSUE TITLE
Public Indexer

### ISSUE THREAD

**Issue by lovetherisk** [taobataoma/meanTorrent#5]
hello
is it possible to use public tracker with DHT enable torrent?
and will it support Mass Tracker Scrapper?
like YiFY was.
how can i contact you?

also for music can u insert "musicbrainz" as it was on What.cd?

**Comment by taobataoma** [comment]
@lovetherisk hi, the meanTorrent is designed for private tracker, so can not support DHT now， May support in the future。
Insert "musicbrainz" is a good idea, I will study it and add into my project. thank u very much.

I you want contact me, please mailto: taobataoma@gmail.com anytime, But there's a 8 hour time difference between us.
