### ISSUE TITLE
(Enhancement) Restrict Views To Auth'ed Users Only

### ISSUE THREAD

**Issue by HDVinnie** [taobataoma/meanTorrent#57]
Right now on signup and register page when not yet authorized one can see all the options in the navigation bar. Torrents/ Forums / Chat / Upload / etc. These should be hidden unless you are authorized(logged in). The only two that should show in the navbar is "Sign In" and "Sign Up".

I also suggest doing the same with the site stats in the footer of the site. These should not show unless you are authorized(logged in).

**Comment by nearsou** [comment]
You can already edit this on ./config/env/torrents.js
```
showMenuHeaderForGuest: true,
showFooterCountInfoForGuest: true,
```

**Comment by HDVinnie** [comment]
cheers.....just was basing what I saw in demo. Figured wasn't optional and if was would be set to false by default seeing MEAN is aimed for private tracker use.
