### ISSUE TITLE
Hit and run

### ISSUE THREAD

**Issue by georgee** [taobataoma/meanTorrent#6]
Hi,your script is very good and i like it much.

Is there any hit and run implement in the next releases?

**Comment by taobataoma** [comment]
hi, @georgee  all hit in the readme.md, if not, You can ask it in more detail，thanks.

**Comment by taobataoma** [comment]
@georgee hi, sorry, I understand your mean about `hit and run` just now, sorry.

let me think about this, because i`m busy, so please wait me new reply.

**Comment by taobataoma** [comment]
@georgee hi, meanTorrent has complete Hit and Run  support now, please check it.

**Comment by georgee** [comment]
It works fine,thank you for your efford!
