### ISSUE TITLE
Deprecated npm packages on node.js 10.x and npm 6.x

### ISSUE THREAD

**Issue by Shadowghost** [taobataoma/meanTorrent#70]
When running the project with node 10.x and npm 6.x (recent stable), npm warns on some installed packages, that they are deprecated and should be upgraded/switched to different ones to be still available in future node releases (and to have a secure environment).
Besides that npm also complains about existing vulnerabilities within the installed packages, which can not be fixed by a simple `npm audit fix`. Not sure if the first problems are really that problematic, but I think the latter one should be taken care of.
What do you think about it?

**Comment by taobataoma** [comment]
@Shadowghost I will upgrade these packages at the right time and test on node10，the modules update was so frequently.
