### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by HDVinnie** [taobataoma/meanTorrent#84]
Demo is down now for weeks. Plan on fixing it?

**Comment by Rhilip** [comment]
@HDVinnie It seems the offical group change their site to https://mine.pt/ without README.md update

**Comment by HDVinnie** [comment]
@Rhilip I see thanks. Should be updated.

**Comment by HDVinnie** [comment]
@Rhilip happen to know the demo login info?

username: demo 
password: demoAdmin12#

Does not seem to work anymore

**Comment by Rhilip** [comment]
@HDVinnie If you means the DEMO site to know this framework, at this moment , May not exist anymore.
One of my friends tall me that they (The offical group of meanTorrent) are using this domain to run a `New Private Site` which provide 1080p or other movie for their members, 
so I don't think the old account of demo site can be used in this site.

**Comment by HDVinnie** [comment]
Thats a shame. Would be nice to have a demo for the codebase. Thanks for the info.
