### ISSUE TITLE
WYSIWYG editor for comments, forums, ...

### ISSUE THREAD

**Issue by darkershares** [taobataoma/meanTorrent#9]
Would be nice to offer a simple rich text editor for user messages, comments, forum posts and so forth. I think for parts of the user base learning Markdown syntax could be a barrier.

I would prefer the rich text editor to be rather lightweight and unobstrusive. TinyMCE and others are powerful but might be overkill in this situation.

#### Possible options:

- [Hallo](https://github.com/bergie/hallo)
- [Quill](https://github.com/quilljs/quill)
- What else…?

#### Potentially useful formatting options:

- P, H1, H2, Code, Pre
- bold, italic, underline
- insert images (hook this up with meanTorrent upload?)
- insert links
- bullet/numbered lists
- quotes
- insert smileys

#### Configuration options:

- Formatting options to show
- Site-wide enable/disable WYSIWYG editor
- Per-user enable/disable WYSIWYG editor

I experimented with Hallo with good results. All the content is saved as Markdown to the database (using [to-markdown](https://github.com/domchristie/to-markdown)).

Would do you think?

**Comment by darkershares** [comment]
[Comparison of JavaScript WYSIWYG editors](https://github.com/dandv/comparisons/blob/master/JavaScript-WYSIWYG-editors.md)

https://alex-d.github.io/Trumbowyg/

**Comment by taobataoma** [comment]
@darkershares thanks for recommend the nice editor to me, I`ll learn it at free time!

**Comment by HDVinnie** [comment]
as a dev myself I prefer WysiBB. Clean and Simple
